#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : goocanvas
Version  : 0.15
Release  : 2
URL      : http://ftp.gnome.org/pub/GNOME/sources/goocanvas/0.15/goocanvas-0.15.tar.bz2
Source0  : http://ftp.gnome.org/pub/GNOME/sources/goocanvas/0.15/goocanvas-0.15.tar.bz2
Summary  : A GTK+ canvas widget using cairo
Group    : Development/Tools
License  : LGPL-2.0
Requires: goocanvas-lib
Requires: goocanvas-doc
Requires: goocanvas-locales
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : gtk+-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libxslt-bin
BuildRequires : perl(XML::Parser)

%description
Welcome to GooCanvas
====================
(a cairo-based canvas widget for GTK+)

%package dev
Summary: dev components for the goocanvas package.
Group: Development
Requires: goocanvas-lib
Provides: goocanvas-devel

%description dev
dev components for the goocanvas package.


%package doc
Summary: doc components for the goocanvas package.
Group: Documentation

%description doc
doc components for the goocanvas package.


%package lib
Summary: lib components for the goocanvas package.
Group: Libraries

%description lib
lib components for the goocanvas package.


%package locales
Summary: locales components for the goocanvas package.
Group: Default

%description locales
locales components for the goocanvas package.


%prep
%setup -q -n goocanvas-0.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1507592213
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1507592213
rm -rf %{buildroot}
%make_install
%find_lang goocanvas

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/goocanvas-1.0/goocanvas.h
/usr/include/goocanvas-1.0/goocanvasellipse.h
/usr/include/goocanvas-1.0/goocanvasenumtypes.h
/usr/include/goocanvas-1.0/goocanvasgrid.h
/usr/include/goocanvas-1.0/goocanvasgroup.h
/usr/include/goocanvas-1.0/goocanvasimage.h
/usr/include/goocanvas-1.0/goocanvasitem.h
/usr/include/goocanvas-1.0/goocanvasitemmodel.h
/usr/include/goocanvas-1.0/goocanvasitemsimple.h
/usr/include/goocanvas-1.0/goocanvasmarshal.h
/usr/include/goocanvas-1.0/goocanvaspath.h
/usr/include/goocanvas-1.0/goocanvaspolyline.h
/usr/include/goocanvas-1.0/goocanvasrect.h
/usr/include/goocanvas-1.0/goocanvasstyle.h
/usr/include/goocanvas-1.0/goocanvastable.h
/usr/include/goocanvas-1.0/goocanvastext.h
/usr/include/goocanvas-1.0/goocanvasutils.h
/usr/include/goocanvas-1.0/goocanvaswidget.h
/usr/lib64/libgoocanvas.so
/usr/lib64/pkgconfig/goocanvas.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/goocanvas/GooCanvas.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasEllipse.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasEllipseModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasGrid.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasGridModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasGroup.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasGroupModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasImage.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasImageModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasItemModelSimple.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasItemSimple.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasPath.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasPathModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasPolyline.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasPolylineModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasRect.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasRectModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasStyle.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasTable.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasTableModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasText.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasTextModel.html
/usr/share/gtk-doc/html/goocanvas/GooCanvasWidget.html
/usr/share/gtk-doc/html/goocanvas/ch01.html
/usr/share/gtk-doc/html/goocanvas/ch02.html
/usr/share/gtk-doc/html/goocanvas/ch03.html
/usr/share/gtk-doc/html/goocanvas/ch04.html
/usr/share/gtk-doc/html/goocanvas/ch05.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-GooCanvas-Types.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-architecture.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-coordinates.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-creating-items.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-goocanvasitem.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-goocanvasitemmodel.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-model-view-canvas.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-overview.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-simple-canvas.html
/usr/share/gtk-doc/html/goocanvas/goocanvas-wysiwyg.html
/usr/share/gtk-doc/html/goocanvas/goocanvas.devhelp
/usr/share/gtk-doc/html/goocanvas/goocanvas.devhelp2
/usr/share/gtk-doc/html/goocanvas/home.png
/usr/share/gtk-doc/html/goocanvas/index.html
/usr/share/gtk-doc/html/goocanvas/index.sgml
/usr/share/gtk-doc/html/goocanvas/left.png
/usr/share/gtk-doc/html/goocanvas/right.png
/usr/share/gtk-doc/html/goocanvas/style.css
/usr/share/gtk-doc/html/goocanvas/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgoocanvas.so.3
/usr/lib64/libgoocanvas.so.3.4.0

%files locales -f goocanvas.lang
%defattr(-,root,root,-)

